blog/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import HomePageView, RecipeView, AboutView, contactView, SubscriptionView, SubscriptionSuccessView, FoodCategoryView, AllCategoriesView

urlpatterns = [
    path ('', HomePageView.as_view(), name='homepage'),
    path ('about/', AboutView.as_view(), name='about'),
    path ('recipes/', AllCategoriesView.as_view(), name='recipes'),
    path ('contact/', contactView, name='contact'),
    path ('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path ('subscription-success/', SubscriptionSuccessView.as_view(), name='subscription_success'),
    path ('<category_url>/', FoodCategoryView.as_view(), name='food_category'),
    path ('<str:category>/<title_slug>/', RecipeView.as_view(), name='recipe'),
    path ("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

muffinmunchies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import BlogPost

info_dict = {
    'queryset': BlogPost.objects.all(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, # new
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.8)}},
        name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify
from django.db import models


class FoodCategory(models.Model):
    category = models.CharField(max_length=40)
    category_url = models.SlugField(max_length=60)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name_plural = "food categories"

class BlogPost(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    food_category = models.ForeignKey('FoodCategory', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='content_images', blank=True)
    medium_image = models.ImageField(upload_to='content_images', blank=True, null=True)
    small_image = models.ImageField(upload_to='content_images', blank=True, null=True)
    image_description = models.CharField(max_length=130)
    date = models.DateTimeField (auto_now_add=True)
    title = models.CharField(max_length=400)
    title_slug = models.SlugField(max_length=60)
    meta_description = models.CharField(max_length=160)
    keywords = models.CharField(max_length=200, blank=True, null=True)
    preview = models.CharField(max_length=180)
    calories = models.CharField(max_length=20, blank=True, null=True)
    preparation_time = models.CharField(max_length=20)
    cooking_time = models.CharField(max_length=20)
    total_time = models.CharField(max_length=20)
    final_quantity = models.CharField(max_length=40)
    text = models.TextField()

    def get_absolute_url (self):
        category = slugify(self.food_category)
        return reverse ('recipe', args=[str(category),str(self.title_slug)])

    def __str__(self):
        return self.title


class RecipePart (models.Model):
    title = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title

class Ingredient (models.Model):
    blog_post = models.ForeignKey('BlogPost', on_delete=models.CASCADE)
    recipe_part = models.ForeignKey('RecipePart', blank=True, null=True, on_delete=models.CASCADE)
    ingredient = models.CharField (max_length=50)
    quantity = models.CharField(max_length=30, blank=True)
    unit = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.ingredient

class RecipeDirections (models.Model):
    blog_post = models.ForeignKey('BlogPost', on_delete=models.CASCADE)
    direction_name = models.CharField (max_length=250, blank=True)
    direction = models.TextField(blank=True)

    def __str__(self):
        return self.direction_name

class NutritionFact (models.Model):
    blog_post = models.OneToOneField('BlogPost', on_delete=models.CASCADE)
    serving_size = models.CharField(max_length=40, blank=True)
    calories = models.CharField(max_length=20, blank=True)
    calories_from_fat = models.CharField(max_length=20, blank=True)
    fat = models.IntegerField(help_text="g",blank=True, null=True)
    saturated_fat = models.IntegerField(help_text="g",blank=True, null=True)
    cholesterol = models.IntegerField(help_text="mg",blank=True, null=True)
    sodium = models.IntegerField(help_text="mg",blank=True, null=True)
    potassium = models.IntegerField(help_text="mg",blank=True, null=True)
    carbohydrates = models.IntegerField(help_text="g",blank=True, null=True)
    fiber = models.IntegerField(help_text="g",blank=True, null=True)
    sugar = models.IntegerField(help_text="g",blank=True, null=True)
    protein = models.IntegerField(help_text="g",blank=True, null=True)
    vitamin_A = models.IntegerField(help_text="mcg",blank=True, null=True)
    calcium = models.IntegerField(help_text="mg",blank=True, null=True)
    iron = models.IntegerField(help_text="mg",blank=True, null=True)

    def __str__(self):
        return self.blog_post.title

class AboutMe (models.Model):
    background_image = models.ImageField(upload_to='content_images', blank=True)
    profile_image = models.ImageField(upload_to='content_images', blank=True)
    image_description = models.CharField(max_length=130, blank=True, null=True)
    side_description = models.TextField(blank=True, null=True)
    full_description = models.TextField(blank=True, null=True)

    def __str__(self):
        self.name = 'Mateja'
        return self.name

class Subscription (models.Model):
    first_name = models.CharField (max_length=30)
    e_mail = models.EmailField (max_length=70)

    def __str__(self):
        return self.e_mail

templates/about.html
{% extends 'base.html' %}
{% block title %}
<title>About me</title>
{% endblock title %}
{% block meta %}
<meta name="description" content="A passionate food blogger and photographer bringing you delicious pastry recipes.">
<meta name="keywords" content="food blog, pastry, recipes, cakes, food photography">
{% endblock meta %}
{% block body %}
{% for about in about_me %}
    <div class="about-blog">
       <div class="container cc-center">
          <div class="w-row">
             <div class="w-col w-col-9 w-col-small-small-stack">
                <div class="text-container">
                   <div class="section-title-big" style="padding-top:100px;">Welcome to MuffinMunchies!</div>
                   <p class="paragraph">{{ about.full_description|safe }}</p>
                </div>
             </div>
             <div class="w-col w-col-3 w-col-small-small-stack">
                <div class="white-wrapper" style="padding-top:100px;">
                    <img src="{{ about.profile_image.url }}" alt="{{ about.image_description }}" class="circle-profile">
                    <div class="sidebar-copy w-richtext">
                       <h1>Mateja Kobescak</h1>
                       <p>{{ about.side_description|safe }}</p>
                       {% endfor %}
                    </div>
                 </div>
             </div>
          </div>
       </div>
    </div>
    <div class="separator">
       <div class="separator-container">
          <div class="line-color"></div>
       </div>
    </div>
    <div class="separator">
       <div class="separator-container">
          <div class="line-color"></div>
       </div>
    </div>
    <div id="contact" class="contact">
       <div class="container">
          <div class="text-container">
             <div class="section-title-big">Get in touch</div>
          </div>
          <div class="contact-wrapper">
             <div class="contact-item-wrapper">
                <div class="contact-item">
                   <div class="contact-number">
                      <div class="number">1</div>
                   </div>
                   <div class="contact-info-subtitle">EMAIL</div>
                   <div class="contact-info-text"><a href="mailto: matejakobescak@gmail.com">matejakobescak@gmail.com</a></div>
                </div>
             </div>
                <div class="contact-item-wrapper">
                   <div class="contact-item">
                      <div class="contact-number">
                         <div class="number">2</div>
                      </div>
                      <div class="contact-info-subtitle">INSTAGRAM</div>
                      <div class="contact-info-text"><a href="https://www.instagram.com/muffinmunchies_/">@muffinmunchies_</a></div>
                   </div>
                </div>
            </div>
          </div>
       </div>
    </div>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
<<<<<<< HEAD
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-FMZFMYPGRG"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-FMZFMYPGRG');
      </script>
=======
       <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FMZFMYPGRG"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-FMZFMYPGRG');
    </script>
>>>>>>> f7dce20a99438a826af57df6341c19c8a8eae400
      <meta charset="utf-8">
      {% block title %}
      {% endblock title %}
      {% block meta %}
      {% endblock meta %}
      {% block jsonld %}
      {% endblock jsonld %}
      <meta content="width=device-width, initial-scale=1" name="viewport">
      <link href="{% static 'css/homepage.css' %}" rel="stylesheet" type="text/css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tenor+Sans:regular%7CSource+Serif+Pro:regular,700%7CLibre+Franklin:regular,600" media="all">
      <script type="text/javascript">WebFont.load({  google: {    families: ["Tenor Sans:regular","Source Serif Pro:regular,700","Libre Franklin:regular,600"]  }});</script><!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif]--><script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
      <link href="#" rel="shortcut icon" type="image/x-icon">
      <link href="#" rel="apple-touch-icon">
      <style>
         body {
         -moz-font-feature-settings: "liga" on;
         -moz-osx-font-smoothing: grayscale;
         -webkit-font-smoothing: antialiased;
         font-feature-settings: "liga" on;
         text-rendering: optimizeLegibility;
         }
      </style>
   </head>
   <body>
    <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navigation w-nav">
       <div class="navigation-container" style="max-height:170px;">
           <!--insert logo image-->
          <a href="/" aria-current="page" class="logo w-inline-block w--current" style="max-width: 100%; height: auto;"><img src="{% static 'images/muffinmunchies-logos_transparent.png' %}" alt="muffinmunchies logo" style="max-width: 300px; max-height: 80px; height: auto;" class="image-logo"/></a>
          <nav role="navigation" class="nav-menu w-nav-menu">
             <a href="{% url 'homepage' %}" aria-current="page" class="navigation-link w-inline-block w--current">
                <div class="navigation-hover" style="opacity: 0; height: 0px;"></div>
                <div class="navigation-link-text">Home</div>
             </a>
             <a href="{% url 'recipes' %}" class="navigation-link w-inline-block">
                <div class="navigation-link-text">Recipes</div>
                <div class="navigation-hover" style="opacity: 0; height: 0px;"></div>
             </a>
             <a href="{% url 'about' %}" class="navigation-link w-inline-block">
                <div class="navigation-link-text">About</div>
                <div class="navigation-hover" style="opacity: 0; height: 0px;"></div>
             </a>
             <a href="{% url 'contact' %}" class="navigation-link w-inline-block">
                <div class="navigation-link-text">Contact</div>
                <div class="navigation-hover" style="opacity: 0; height: 0px;"></div>
             </a>
          </nav>
          <div class="menu-button w-nav-button" style="-webkit-user-select: text;" aria-label="menu" role="button" tabindex="0" aria-controls="w-nav-overlay-0" aria-haspopup="menu" aria-expanded="false">
             <div class="icon-2 w-icon-nav-menu"></div>
          </div>
       </div>
       <div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div>
    </div>
    {% block body %}
    {% endblock body %}
    <div class="footer">
        <div class="container-footer">
           <div class="container">
              <div class="top-section">
                  <!--Insert logo-->
                 <div class="footer-small-text">© 2022 Muffin Munchies, all rights reserved</div>
              </div>
           </div>
           <div class="separator-footer">
              <div class="separator-color footer-line"></div>
           </div>
           <div class="container">
              <div class="bottom">
                 <div class="bottom-1">
                    <div data-delay="0" class="dropdown w-dropdown">
                       <div class="dropdown-toggle w-dropdown-toggle" id="w-dropdown-toggle-0" aria-controls="w-dropdown-list-0" aria-haspopup="menu" aria-expanded="false" role="button" tabindex="0">
                          <div class="icon w-icon-dropdown-toggle"></div>
                          <div>Category</div>
                       </div>
                       <nav class="dropdown-list w-dropdown-list" id="w-dropdown-list-0" aria-labelledby="w-dropdown-toggle-0">
                          <div class="w-dyn-list">
                             <div role="list" class="w-dyn-items">
                                 {% for food_category in food_categories %}
                                <div role="listitem" class="dropdown-link w-dyn-item"><a href="{% url 'food_category' food_category.category_url %}" class="dropdown-link-text" tabindex="0">{{ food_category.category }}</a></div>
                                {% endfor %}
                             </div>
                          </div>
                       </nav>
                    </div>
                    <div class="footer-categories">
                       <div class="footer-title-text">Categories</div>
                       <div class="footer-links-container cc-categories">
                          <div class="w-dyn-list">
                             <div role="list" class="collection-list w-dyn-items">
                               {% for food_category in food_categories %}
                                <div role="listitem" class="footer-collection-item w-dyn-item"><a href="{% url 'food_category' food_category.category_url %}" class="link-footer">{{ food_category.category }}</a></div>
                                {% endfor %}
                             </div>
                          </div>
                       </div>
                    </div>
                    <div class="footer-newsletter">
                       <a href="{% url 'subscribe' %}"><div class="footer-title-text w-button" style="color:#000000; background-color:#ffffff">Subscribe to newsletter</div></a>
                    </div>
                 </div>
                 <div class="bottom-2">
                    <div class="footer-links-container">
                       <div class="footer-links">
                          <div class="footer-title-text">Information</div>
                          <div class="footer-links-inner"><a href="/about" class="nav-link white">about</a><a href="http://blog-b132a3.webflow.io/about#contact" class="nav-link white">contact</a><a href="#" class="nav-link white">terms</a></div>
                       </div>
                       <div class="footer-links">
                          <div class="footer-title-text">follow us</div>
                          <div class="footer-links-inner"><a href="https://www.instagram.com/muffinmunchies_/" class="nav-link white">instagram</a>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
     <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5f42726f7b8afa3bb38ca7d0" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://uploads-ssl.webflow.com/5f42726f7b8afa3bb38ca7d0/js/webflow.db93aadc3.js" type="text/javascript"></script>
     <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
    </body>
    </html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
<title>About me</title>
{% endblock title %}
{% block meta %}
<meta name="description" content="A passionate food blogger and photographer bringing you delicious pastry recipes.">
<meta name="keywords" content="food blog, pastry, recipes, cakes, food photography">
{% endblock meta %}
{% block body %}
<div class="introductory-text" style="padding-left:8px; padding-right:8px;">
    <div class="container">
       <div class="posts-wrapper cc-top-post">
          <h1 class="heading" style="text-align: center;">Welcome to MuffinMunchies!</h1>
       </div>
    </div>
 </div>
<div class="about-blog" style="padding: 20px;">
   <div class="container cc-center">
      <div class="w-row">
         <div class="w-col w-col-11 w-col-small-small-stack">
             <p>If you have any questions regarding the recipes, you're interested
                in working with me or you just want to say hello - feel free to contact
                me via e-mail or on Instagram. I'd love to hear from you!</p>
            <!-- removed form until I fix it <div class="text-container" style="width:100%;word-break: break-all;">
               <form method="post">{% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Submit" class="submit-button w-button">
            </form>
            </div>
            <div class="separator">
                <div class="separator-container" style="padding-bottom: 60px;">
                </div>
             </div>-->
         </div>
      </div>
   </div>
</div>
<div class="separator">
   <div class="separator-container">
      <div class="line-color"></div>
   </div>
</div>
<div id="contact" class="contact" style="padding-top:20px;">
   <div class="container">
      <div class="text-container">
         <div class="section-title-big">Get in touch via E-mail and Instagram</div>
      </div>
      <div class="contact-wrapper">
         <div class="contact-item-wrapper">
            <div class="contact-item">
               <div class="contact-number">
                  <div class="number">1</div>
               </div>
               <div class="contact-info-subtitle">EMAIL</div>
               <div class="contact-info-text"><a href="mailto: matejakobescak@gmail.com">matejakobescak@gmail.com</a></div>
            </div>
         </div>
            <div class="contact-item-wrapper">
               <div class="contact-item">
                  <div class="contact-number">
                     <div class="number">2</div>
                  </div>
                  <div class="contact-info-subtitle">INSTAGRAM</div>
                  <div class="contact-info-text"><a href="https://www.instagram.com/muffinmunchies_/">@muffinmunchies_</a></div>
               </div>
            </div>
        </div>
      </div>
   </div>
</div>
{% endblock body %}

templates/food_category.html
{% extends "base.html" %}
{% block body %}
<div class="introductory-text">
    <div class="container">
       <div class="posts-wrapper cc-top-post">
          <h1 class="heading" style="text-align: left;">{{current_category.category|title}}</h1>
       </div>
    </div>
 </div>
 <div class="_3-posts">
    <div class="container">
       <div class="posts-wrapper">
          <div class="posts-collection-list-wrapper w-dyn-list">
             <div role="list" class="posts-collection-list w-dyn-items w-row">
                 {% for post in food_category %}
                <div role="listitem" class="_3-collection-item w-dyn-item w-col w-col-4">
                   <a href="{% url 'recipe' post.food_category post.title_slug %}" class="posts-image w-inline-block"><img src="{{ post.image.url }}" alt="{{ post.image_description }}" style="width: 100%; max-height: 300px; object-fit: cover; border-radius: 15px;"></a>
                   <div class="post-info-text">
                      <a href="{% url 'recipe' post.food_category post.title_slug %}" class="post-title w-inline-block">
                         <h3 class="h3">{{ post.title }}</h3>
                      </a>
                      <div class="post-short-text">{{ post.preview }}</div>
                      <div class="post-author-text cc-small-thumbnail">
                        {% if post.total_time %}
                         <div class="post-author cc-top-margin" style="font-size: 14px;">Total time:</div>
                         <div class="post-author" style="font-size: 14px;">{{ post.total_time }}</div>
                        {% endif %}
                        {% if post.calories %}
                        <div class="post-author cc-top-margin" style="font-size: 14px;"> &nbsp;| Calories:</div>
                        <div class="post-author" style="font-size: 14px;">{{ post.calories }}</div>
                        {% endif %}
                      </div>
                   </div>
                </div>
                {% endfor %}
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
 <div class="separator">
    <div class="separator-container">
       <div class="line-color"></div>
    </div>
 </div>
{% endblock body %}

templates/homepage.html
{% extends 'base.html' %}
{% block title %}
<title>Muffin Munchies</title>
{% endblock title %}
{% block meta %}
<meta name="description" content="Food blog writing about pastry: muffins, cakes, pancakes">
<meta name="keywords" content="food blog, muffins, cakes, pancakes, pastry">
{% endblock meta %}
{% block body %}
      <div class="introductory-text">
         <div class="container">
            <div style="text-align: center;">
               {% for food_category in food_categories %}
               <div style="margin-bottom: 15px; display: inline-block;">
                  <a href="{% url 'food_category' food_category.category_url %}" class="category-link button-hover" style="border: 1px solid #999; border-radius: 15px; padding: 5px 15px; text-decoration: none; font-size: 14px; margin: 5px;">{{ food_category.category|upper }}</a>
               </div>
               {% endfor %}
            </div>
         </div>
      </div>
      <div class="separator">
         <div class="separator-container">
            <div class="line-color"></div>
         </div>
      </div>
      <div class="top-post">
         <div class="container">
            <div class="posts-wrapper cc-top-post">
               <div class="w-dyn-list">
                  <div role="list" class="w-dyn-items">
                     <div role="listitem" class="top-post-item w-dyn-item">
                        <a href="{% url 'recipe' most_recent_post.food_category.category_url most_recent_post.title_slug %}" class="top-post-image w-inline-block"><img src="{{ most_recent_post.medium_image.url }}" alt="{{ most_recent_post.image_description }}" srcset="{{ most_recent_post.medium_image.url }} 640w, {{ most_recent_post.image.url }} 1024w" class="post-image" style="width:100%; max-height: 470px; object-fit: cover; border-radius: 15px;"></a>
                        <div class="top-post-text">
                            {% if most_recent_post %}
                           <a href="{% url 'food_category' most_recent_post.food_category.category_url %}" class="category-link">{{ most_recent_post.food_category }}</a>
                           <a href="{% url 'recipe' most_recent_post.food_category.category_url most_recent_post.title_slug %}" class="top-post-link-block w-inline-block">
                              <h2 class="h2">{{ most_recent_post.title}}</h2>
                           </a>
                           <div class="post-short-text">{{ most_recent_post.preview }}</div>
                           <div class="post-author-text">
                              <div class="post-author cc-top-margin">By</div>
                              <a href="{% url 'about' %}" class="post-author">{{ most_recent_post.author }}</a>
                           </div>
                           {% endif %}
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="_3-posts">
         <div class="container">
            <div class="posts-wrapper">
               <div class="posts-collection-list-wrapper w-dyn-list">
                  <div role="list" class="posts-collection-list w-dyn-items w-row">
                      {% for post in other_posts %}
                     <div role="listitem" class="_3-collection-item w-dyn-item w-col w-col-4">
                        <a href="{% url 'recipe' post.food_category post.title_slug %}" class="posts-image w-inline-block"><img src="{{ post.image.url }}" alt="{{ post.image_description }}" style="width:100%; max-height: 300px; object-fit: cover; border-radius: 15px;"></a>
                        <div class="post-info-text">
                           <a href="{% url 'food_category' post.food_category %}" class="category-link">{{ post.food_category }}</a>
                           <a href="{% url 'recipe' post.food_category post.title_slug %}" class="post-title w-inline-block">
                              <h3 class="h3">{{ post.title }}</h3>
                           </a>
                           <div class="post-author-text cc-small-thumbnail">
                              <div class="post-author cc-top-margin">By</div>
                              <a href="#" class="post-author">{{ post.author }}</a>
                           </div>
                        </div>
                     </div>
                     {% endfor %}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="separator">
         <div class="separator-container">
            <div class="line-color"></div>
         </div>
      </div>
{% endblock body %}

templates/recipes_by_category.html
{% extends "base.html" %}
{% block body %}
<div style="padding-top: 80px;"></div>
 {% for category in proba %}
 <div class="introductory-text" style="padding-top: 20px;">
    <div class="container">
       <div class="posts-wrapper cc-top-post">
          <h1 class="heading" style="text-align: left; border-bottom: 1px solid #999;">{{ category.category|title}}</h1>
       </div>
    </div>
 </div>
 <div class="_3-posts">
    <div class="container">
       <div class="posts-wrapper">
          <div class="posts-collection-list-wrapper w-dyn-list">
             <div role="list" class="posts-collection-list w-dyn-items w-row">
                 {% for post in category.blogpost_set.all %}
                <div role="listitem" class="_3-collection-item w-dyn-item w-col w-col-4">
                   <a href="{% url 'recipe' post.food_category post.title_slug %}" class="posts-image w-inline-block"><img src="{{ post.image.url }}" alt="{{ post.image_description }}" style="width: 100%; max-height: 300px; object-fit: cover; border-radius: 15px;"></a>
                   <div class="post-info-text">
                      <a href="{% url 'recipe' post.food_category post.title_slug %}" class="post-title w-inline-block">
                         <h3 class="h3">{{ post.title }}</h3>
                      </a>
                      <div class="post-short-text">{{ post.preview }}</div>
                      <div class="post-author-text cc-small-thumbnail">
                        {% if post.total_time %}
                         <div class="post-author cc-top-margin" style="font-size: 14px;">Total time:</div>
                         <div class="post-author" style="font-size: 14px;">{{ post.total_time }}</div>
                        {% endif %}
                        {% if post.calories %}
                        <div class="post-author cc-top-margin" style="font-size: 14px;"> &nbsp;| Calories:</div>
                        <div class="post-author" style="font-size: 14px;">{{ post.calories }}</div>
                        {% endif %}
                      </div>
                   </div>
                </div>
                {% endfor %}
                {% if category.blogpost_set.count > 3 %}
                <div style="width: 100%;">
                <div class="footer-newsletter" style="display: block; text-align: center; margin: 0px auto;">
                  <a href="{% url 'food_category' category.category_url %}" class="button-hover footer-title-text category-link" style="border: 1px solid #999; font-size: 18px; border-radius: 15px; padding: 5px 15px; display: block; text-align: center; line-height: 20px; text-decoration: none;">See all {{ category.category }}</a>
               </div>
               {% endif %}
            </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
 {% endfor %}
 <div class="separator">
    <div class="separator-container">
       <div class="line-color"></div>
    </div>
 </div>
{% endblock body %}

templates/subscription_success.html
{% extends 'base.html' %}
{% block title %}
<title>You've subscribed successfully!</title>
{% endblock title %}
{% block meta %}
<meta name="description" content="A passionate food blogger and photographer bringing you delicious pastry recipes.">
<meta name="keywords" content="food blog, pastry, recipes, cakes, food photography">
{% endblock meta %}
{% block body %}
<div class="introductory-text" style="padding-left:8px; padding-right:8px; padding-bottom: 350px;">
    <div class="container">
       <div class="posts-wrapper cc-top-post">
          <h1 class="heading" style="text-align: center;">You have successfully subscribed!</h1>
          <meta http-equiv="refresh" content="2;url={% url 'homepage' %}"> 
       </div>
    </div>
 </div>
{% endblock body %}